services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nest-db
    volumes:
      - ../taskFlow-db/:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/nest-db
      ME_CONFIG_BASICAUTH: false

  backend:
    build: ./backend
    restart: always
    volumes:
    - ./backend/src:/app/src
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://mongo:27017/nest-db
      MONGODB_NAME: nest-db
      PORT: 3000

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - 4200:4200
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: '1.0'
  #   volumes:
  #     - ./frontend/src:/app/src